name: dotnet pr format

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  ut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Run clean code
        run: |
          dotnet tool restore
          dotnet restore
          dotnet tool run jb cleanupcode --verbosity=INFO --exclude=**Tests/**.* $(git diff --name-only origin/main)
          git add .
          if [ -n "$(git status --porcelain)" ]; then
              git config --global user.name 'ReSharper CLI CleanupCode GitHub Action'
              git config --global user.email 'niceformate@nice.com'
              git commit -m "Cleanup code by ReSharper CLI CleanupCode GitHub Action"
              git push origin HEAD:${{ github.head_ref }}
          else
              echo "No changes detected"
          fi